<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="40983696-89c5-4327-bdc8-8fb2e1fc7b20" name="ggilmour@INSTILSNGLAPTOP 2013-05-15 13:47:26" runUser="InstilSngLaptop\ggilmour" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="485879c6-563f-4449-9e13-f51cd5798057">
    <Description>These are default test settings for a local test run.</Description>
    <Execution>
      <TestTypeSpecific>
        <UnitTestRunConfig testTypeId="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b">
          <AssemblyResolution>
            <TestDirectory useLoadContext="true" />
          </AssemblyResolution>
        </UnitTestRunConfig>
      </TestTypeSpecific>
      <AgentRule name="LocalMachineDefaultRole">
      </AgentRule>
    </Execution>
    <Deployment runDeploymentRoot="ggilmour_INSTILSNGLAPTOP 2013-05-15 13_47_26" />
  </TestSettings>
  <Times creation="2013-05-15T13:47:26.2098242+01:00" queuing="2013-05-15T13:47:26.4523987+01:00" start="2013-05-15T13:47:26.6745470+01:00" finish="2013-05-15T13:47:27.2349218+01:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <DebugTrace>E, 7328, 32, 2013/05/15, 13:47:27.146, INSTILSNGLAPTOP\QTAgent32.exe, Could not find file 'C:\Development\DotNet\FullyVS2010\CourseProjects\Agile\DataDrivenTesting\TestResults\ggilmour_INSTILSNGLAPTOP 2013-05-15 13_47_26\Out\Input.xml'. for XML data source |DataDirectory|\TestData\Input.xml
</DebugTrace>
    </Output>
    <RunInfos>
      <RunInfo computerName="INSTILSNGLAPTOP" outcome="Warning" timestamp="2013-05-15T13:47:26.4523987+01:00">
        <Text>Warning: Test Run deployment issue: Failed to get the file for deployment item '\TestData\Input.xml' specified by the test 'DataDrivenTesting.SampleTest.DataDrivenTest': System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\TestData\Input.xml'.</Text>
        <Exception>System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\TestData\Input.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at Microsoft.VisualStudio.TestTools.Common.SingleFileProvider.GetFilePaths()
   at Microsoft.VisualStudio.TestTools.TestManagement.DeploymentCoverageItem.GetFiles(TestRunConfiguration runConfig)
   at Microsoft.VisualStudio.TestTools.TestManagement.DeploymentManager.DoDeployment(TestRun run, FileCopyService fileCopyService)</Exception>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="DataDrivenTest" storage="c:\development\dotnet\fullyvs2010\courseprojects\agile\datadriventesting\writingdatadriventests\bin\debug\writingdatadriventests.dll" id="b029f1fb-f70d-6cb7-be99-82efd4f81ed6">
      <DeploymentItems>
        <DeploymentItem filename="\TestData\Input.xml" />
      </DeploymentItems>
      <Execution id="78d47ae6-0cdf-47c8-9da5-5bd505ad696b" />
      <TestMethod codeBase="C:/Development/DotNet/FullyVS2010/CourseProjects/Agile/DataDrivenTesting/WritingDataDrivenTests/bin/Debug/WritingDataDrivenTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="DataDrivenTesting.SampleTest, WritingDataDrivenTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="DataDrivenTest" />
      <DataSource connectionString="|DataDirectory|\TestData\Input.xml" providerInvariantName="Microsoft.VisualStudio.TestTools.DataSource.XML" tableName="Employee" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="b029f1fb-f70d-6cb7-be99-82efd4f81ed6" executionId="78d47ae6-0cdf-47c8-9da5-5bd505ad696b" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="78d47ae6-0cdf-47c8-9da5-5bd505ad696b" testId="b029f1fb-f70d-6cb7-be99-82efd4f81ed6" testName="DataDrivenTest" computerName="INSTILSNGLAPTOP" startTime="2013-05-15T13:47:26.5124396+01:00" endTime="2013-05-15T13:47:27.1858890+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="78d47ae6-0cdf-47c8-9da5-5bd505ad696b" resultType="DataDrivenTest">
      <Output>
        <ErrorInfo>
          <Message>The unit test adapter failed to connect to the data source or to read the data. For more information on troubleshooting this error, see "Troubleshooting Data-Driven Unit Tests" (http://go.microsoft.com/fwlink/?LinkId=62412) in the MSDN Library.
Error details: Object reference not set to an instance of an object.</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>